name: Static Analysis & Formatting

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    static-analysis:
        name: Run Spotless and Detekt Checks
        runs-on: macOS-latest
        steps:
            -   name: Check out code
                uses: actions/checkout@v4

            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    distribution: 'zulu'
                    java-version: 21

            -   name: Cache Gradle files
                uses: actions/cache@v3
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

            -   name: Run Spotless Check
                run: ./gradlew spotlessCheck --stacktrace
